### ISSUE TITLE
AWS_IO_TLS_CTX_ERROR while mounting

### ISSUE THREAD

**Issue by maxemontio** [awslabs/mountpoint-s3-csi-driver#241] opened 2024-08-22 13:10 UTC
Hi!

When i try to mount a PVC to a pod, i am getting the error:
```
MountVolume.SetUp failed for volume "s3-pv" : rpc error: code = Internal desc = Could not mount "<redacted>" at "/var/lib/kubelet/pods/116ccb23-c268-4c4b-9396-4e78143251a5/volumes/kubernetes.io~csi/s3-pv/mount": Mount failed: Failed to start service output: Error: Failed to create S3 client Caused by: 0: invalid AWS credentials 1: CRT error 1033: aws-c-io: AWS_IO_TLS_CTX_ERROR, Failed to create tls context Error: Failed to create mount process
```
logs from the pod:
```
I0822 12:39:15.074277       1 node.go:65] NodePublishVolume: req: volume_id:"s3-csi-driver-volume" target_path:"/var/lib/kubelet/pods/116ccb23-c268-4c4b-9396-4e78143251a5/volumes/kubernetes.io~csi/s3-pv/mount" volume_capability:<mount:<mount_flags:"allow-other" mount_flags:"allow-delete" mount_flags:"region us-east-1" mount_flags:"prefix tmp/" > access_mode:<mode:MULTI_NODE_MULTI_WRITER > > volume_context:<key:"bucketName" value:"<redacted>" > 
I0822 12:39:15.074323       1 node.go:112] NodePublishVolume: mounting <redacted> at /var/lib/kubelet/pods/116ccb23-c268-4c4b-9396-4e78143251a5/volumes/kubernetes.io~csi/s3-pv/mount with options [--allow-delete --allow-other --prefix=tmp/ --region=us-east-1]
E0822 12:39:15.115224       1 driver.go:113] GRPC error: rpc error: code = Internal desc = Could not mount "<redacted>" at "/var/lib/kubelet/pods/116ccb23-c268-4c4b-9396-4e78143251a5/volumes/kubernetes.io~csi/s3-pv/mount": Mount failed: Failed to start service output: Error: Failed to create S3 client  Caused by:     0: invalid AWS credentials     1: CRT error 1033: aws-c-io: AWS_IO_TLS_CTX_ERROR, Failed to create tls context Error: Failed to create mount process
```

We use IRSA.

values.yaml:
```
node:
  serviceAccount:
    create: true
    name: s3-csi-driver-sa
    annotations:
      "eks.amazonaws.com/role-arn": <redacted>
  resources:
    requests:
      cpu: null
      memory: 32Mi
    limits:
      cpu: null
      memory: 256Mi
  tolerateAllTaints: false

sidecars:
  nodeDriverRegistrar:
    resources:
      requests:
        cpu: null
        memory: 32Mi
      limits:
        cpu: null
        memory: 128Mi
  livenessProbe:
    resources:
      requests:
        cpu: null
        memory: 32Mi
      limits:
        cpu: null
        memory: 128Mi
```
iam policy:
```
{
    "Statement": [
        {
            "Action": "s3:ListBucket",
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::*",
            "Sid": "MountpointFullBucketAccess"
        },
        {
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:AbortMultipartUpload"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::*/*",
            "Sid": "MountpointFullObjectAccess"
        }
    ],
    "Version": "2012-10-17"
}
```
trust policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::<redacted>:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/<redacted_id>"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-east-1.amazonaws.com/id/<redacted_id>:aud": "sts.amazonaws.com",
                    "oidc.eks.us-east-1.amazonaws.com/id/<redacted_id>:sub": "system:serviceaccount:aws-mountpoint-s3-csi-driver:s3-csi-driver-sa"
                }
            }
        }
    ]
}
```
This is what i use for testing:
```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - allow-other
    - allow-delete
    - region us-east-1
    - prefix tmp/
  csi:
    driver: s3.csi.aws.com
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: <redacted>

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: s3-pv

---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: s3-pvc
  containers:
    - name: ubuntu
      image: ubuntu
      command:
        - "sleep"
        - "604800"
      volumeMounts:
        - name: data
          mountPath: /mnt/data
```
What could it be? We have another apps which are using irsa without any problem in the same cluster. It looks more like a tls error than a configuration error.

**Environment**
- Driver version: 1.8.0
- Kubernetes EKS version: 1.29
- Kubelet version: v1.29.3-eks-ae9a62a
- Containerd version: containerd://1.7.11
- OS: Amazon Linux 2
- Ami version: [v20240703](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20240703)

**Comment by unexge** [comment] 2024-08-22 13:19
Hey @maxemontio, thanks for reporting the issue! 

Were you experiencing the same issue with other version as well or did it start happening with 1.8.0? 

The error seems like originates from the CRT, would you be able to share some CRT logs with us by passing `debug-crt` to your `mountOptions`? You can find more details from here: https://github.com/awslabs/mountpoint-s3/blob/main/doc/TROUBLESHOOTING.md#credentials-errors

**Comment by maxemontio** [comment] 2024-08-23 09:28
Hey @unexge

I have checked all minor versions starting from 1.6.0, the same error is present.

Passing `debug-crt` to `mountOptions` for some reason didn't give me any extra logs in pods or somewhere else, so i had to launch `mount-s3` manually, directly from the node. I used [this](https://github.com/awslabs/mountpoint-s3/blob/main/doc/CONFIGURATION.md#aws-credentials) instruction.
```
# /opt/mountpoint-s3-csi/bin/mount-s3 --debug-crt -f <redacted> --prefix /tmp/ /mnt --region us-east-1 --profile s3
...
2024-08-23T08:26:34.968572Z  INFO awscrt::dns: id=0x55e041b79cd0: Initializing default host resolver with 8 max host entries.    
2024-08-23T08:26:34.968580Z DEBUG awscrt::event-loop: id=0x55e041da4d10: exiting main loop    
2024-08-23T08:26:34.968588Z  INFO awscrt::channel-bootstrap: id=0x55e041cc7d80: Initializing client bootstrap with event-loop group 0x55e041b7d590    
2024-08-23T08:26:34.968598Z  INFO awscrt::standard-retry-strategy: static: creating new standard retry strategy    
2024-08-23T08:26:34.968609Z  INFO awscrt::event-loop: id=0x55e041ba2e00: main loop started    
2024-08-23T08:26:34.968622Z  INFO awscrt::event-loop: id=0x55e041ba2e00: default timeout 100000, and max events to process per tick 100    
2024-08-23T08:26:34.968635Z  INFO awscrt::standard-retry-strategy: id=0x55e041cd4d30: creating backing exponential backoff strategy with max_retries of 9    
2024-08-23T08:26:34.968644Z  INFO awscrt::exp-backoff-strategy: id=0x55e041cc7c90: Initializing exponential backoff retry strategy with scale factor: 500 jitter mode: 2 and max retries 9    
2024-08-23T08:26:34.968653Z DEBUG awscrt::standard-retry-strategy: id=0x55e041cd4d30: maximum bucket capacity set to 500    
2024-08-23T08:26:34.968666Z DEBUG awscrt::AWSProfile: Creating profile collection from file at "/root/.aws/config"    
2024-08-23T08:26:34.968696Z DEBUG awscrt::AWSProfile: Creating profile collection from file at "/root/.aws/credentials"    
2024-08-23T08:26:34.968710Z ERROR awscrt::common-io: static: Failed to open file. path:'/root/.aws/credentials' mode:'rb' errno:2 aws-error:44(AWS_ERROR_FILE_INVALID_PATH)    
2024-08-23T08:26:34.968718Z DEBUG awscrt::AWSProfile: Failed to read file at "/root/.aws/credentials"    
2024-08-23T08:26:34.968727Z DEBUG awscrt::AWSProfile: property "role_arn" has value "" replaced during merge    
2024-08-23T08:26:34.968736Z DEBUG awscrt::AWSProfile: property "credential_source" has value "" replaced during merge    
2024-08-23T08:26:34.968747Z  INFO awscrt::AuthCredentialsProvider: static: profile s3 has role_arn property is set to arn:aws:iam::<redacted>:role/aws-mountpoint-s3-csi-driver-<redacted>, attempting to create an STS credentials provider.    
2024-08-23T08:26:34.968756Z DEBUG awscrt::AuthCredentialsProvider: static: computed session_name as aws-common-runtime-profile-config-3040303    
2024-08-23T08:26:34.968764Z  INFO awscrt::AuthCredentialsProvider: TLS context not provided, initializing a new one for querying STS    
2024-08-23T08:26:34.968816Z ERROR awscrt::tls-handler: ctx: configuration error: Error initializing trust store (Error encountered in /workplace/mountpoint-s3/mountpoint-s3-crt-sys/crt/s2n-tls/tls/s2n_x509_validator.c:127)    
2024-08-23T08:26:34.968827Z ERROR awscrt::tls-handler: Failed to set ca_path: /etc/ssl/certs and ca_file /etc/ssl/certs/ca-certificates.crt
2024-08-23T08:26:34.968838Z DEBUG awscrt::channel-bootstrap: id=0x55e041cc7d80: releasing bootstrap reference    
2024-08-23T08:26:34.968846Z DEBUG awscrt::channel-bootstrap: id=0x55e041cc7d80: bootstrap destroying    
2024-08-23T08:26:34.968885Z  INFO awscrt::event-loop: id=0x55e041ba2e00: Destroying event_loop    
2024-08-23T08:26:34.968893Z  INFO awscrt::event-loop: id=0x55e041ba2e00: Stopping event-loop thread.    
2024-08-23T08:26:34.968913Z DEBUG awscrt::event-loop: id=0x55e041ba2e00: exiting main loop    
2024-08-23T08:26:34.968935Z  INFO awscrt::event-loop: id=0x55e041ba3710: Destroying event_loop    
2024-08-23T08:26:34.968942Z  INFO awscrt::event-loop: id=0x55e041ba3710: Stopping event-loop thread.    
2024-08-23T08:26:34.968973Z DEBUG awscrt::event-loop: id=0x55e041ba3710: exiting main loop    
2024-08-23T08:26:34.969010Z  INFO awscrt::event-loop: id=0x55e041ce3820: Destroying event_loop    
2024-08-23T08:26:34.969018Z  INFO awscrt::event-loop: id=0x55e041ce3820: Stopping event-loop thread.    
Error: Failed to create S3 client

Caused by:
    0: invalid AWS credentials
    2024-08-23T08:26:34.969066Z DEBUG awscrt::event-loop: id=0x55e041ce3820: exiting main loop    
1: CRT error 1033: aws-c-io: AWS_IO_TLS_CTX_ERROR, Failed to create tls context
2024-08-23T08:26:34.969115Z  INFO awscrt::event-loop: id=0x55e041ba4130: Destroying event_loop    
2024-08-23T08:26:34.969123Z  INFO awscrt::event-loop: id=0x55e041ba4130: Stopping event-loop thread.    
2024-08-23T08:26:34.969140Z DEBUG awscrt::event-loop: id=0x55e041ba4130: exiting main loop    
```

If i add `--no-sign-request` option i get this:
```
...
2024-08-23T09:19:55.442021Z  INFO awscrt::event-loop: id=0x55a55f767190: Starting event-loop thread.    
2024-08-23T09:19:55.442045Z DEBUG awscrt::event-loop: id=0x55a55f95f0a0: exiting main loop    
2024-08-23T09:19:55.442070Z  INFO awscrt::dns: id=0x55a55f8308e0: Initializing default host resolver with 8 max host entries.    
2024-08-23T09:19:55.442093Z  INFO awscrt::event-loop: id=0x55a55f767190: main loop started    
2024-08-23T09:19:55.442134Z  INFO awscrt::channel-bootstrap: id=0x55a55f8dd970: Initializing client bootstrap with event-loop group 0x55a55f8d22f0    
2024-08-23T09:19:55.442142Z  INFO awscrt::event-loop: id=0x55a55f767190: default timeout 100000, and max events to process per tick 100    
2024-08-23T09:19:55.442181Z  INFO awscrt::standard-retry-strategy: static: creating new standard retry strategy    
2024-08-23T09:19:55.442257Z  INFO awscrt::standard-retry-strategy: id=0x55a55f8840c0: creating backing exponential backoff strategy with max_retries of 9    
2024-08-23T09:19:55.442271Z  INFO awscrt::exp-backoff-strategy: id=0x55a55f74b430: Initializing exponential backoff retry strategy with scale factor: 500 jitter mode: 2 and max retries 9    
2024-08-23T09:19:55.442290Z DEBUG awscrt::standard-retry-strategy: id=0x55a55f8840c0: maximum bucket capacity set to 500    
2024-08-23T09:19:55.442416Z DEBUG awscrt::channel-bootstrap: id=0x55a55f8dd970: acquiring bootstrap reference    
2024-08-23T09:19:55.442978Z ERROR awscrt::tls-handler: ctx: configuration error: Error initializing trust store (Error encountered in /workplace/mountpoint-s3/mountpoint-s3-crt-sys/crt/s2n-tls/tls/s2n_x509_validator.c:127)    
2024-08-23T09:19:55.442991Z ERROR awscrt::tls-handler: Failed to set ca_path: /etc/ssl/certs and ca_file /etc/ssl/certs/ca-certificates.crt
2024-08-23T09:19:55.443002Z DEBUG awscrt::channel-bootstrap: id=0x55a55f8dd970: releasing bootstrap reference    
2024-08-23T09:19:55.443010Z DEBUG awscrt::channel-bootstrap: id=0x55a55f8dd970: releasing bootstrap reference    
2024-08-23T09:19:55.443018Z DEBUG awscrt::channel-bootstrap: id=0x55a55f8dd970: bootstrap destroying    
2024-08-23T09:19:55.443078Z  INFO awscrt::event-loop: id=0x55a55f767190: Destroying event_loop    
2024-08-23T09:19:55.443092Z  INFO awscrt::event-loop: id=0x55a55f767190: Stopping event-loop thread.    
2024-08-23T09:19:55.443116Z DEBUG awscrt::event-loop: id=0x55a55f767190: exiting main loop    
2024-08-23T09:19:55.443211Z  INFO awscrt::event-loop: id=0x55a55f7601a0: Destroying event_loop    
2024-08-23T09:19:55.443220Z  INFO awscrt::event-loop: id=0x55a55f7601a0: Stopping event-loop thread.    
2024-08-23T09:19:55.443247Z DEBUG awscrt::event-loop: id=0x55a55f7601a0: exiting main loop    
Error: 2024-08-23T09:19:55.443314Z  INFO awscrt::event-loop: id=0x55a55f7d1a80: Destroying event_loop    
Failed to create S3 client2024-08-23T09:19:55.443343Z  INFO awscrt::event-loop: id=0x55a55f7d1a80: Stopping event-loop thread.    


Caused by:
   2024-08-23T09:19:55.443379Z DEBUG awscrt::event-loop: id=0x55a55f7d1a80: exiting main loop    
 0: Unknown CRT error2024-08-23T09:19:55.443461Z  INFO awscrt::event-loop: id=0x55a55f766970: Destroying event_loop    

2024-08-23T09:19:55.443476Z  INFO awscrt::event-loop: id=0x55a55f766970: Stopping event-loop thread.    
    1: CRT error 1033: aws-c-io: AWS_IO_TLS_CTX_ERROR, Failed to create tls context
```
I expected to get some sort of 403 because it is not a public bucket and it requires authentication, but it didn't get up to that point.

**Comment by unexge** [comment] 2024-08-23 15:14
Hey @maxemontio, thanks for the detailed logs.

Looks like the CRT is trying to load your system's default trust store at `/etc/ssl/certs` and `/etc/ssl/certs/ca-certificates.crt`, but fails to load.

Do you have `ca-certificates` package installed (`yum install ca-certificates`) in your host? And do you have any specific trust store installed?

**Comment by maxemontio** [comment] 2024-08-27 11:47
Sorry for such a delay @unexge 

Sure i have it installed:
```
# yum list installed | grep ca-certificates
ca-certificates.noarch               2023.2.64-1.amzn2.0.1           installed  
```
Updating it to the latest available version (`2023.2.68-1.amzn2.0.1`) in repos doesn't make any difference.

There is no any special thing about certificates in the system. I only add our internal CA by putting it to `/etc/pki/ca-trust/source/anchors/` and running `update-ca-trust`.

**Comment by unexge** [comment] 2024-08-27 13:55
Hey @maxemontio, is your internal CA in PEM format? I tried creating a private CA using [AWS Private Certificate Authority](https://aws.amazon.com/private-ca/), and it worked for me. I basically followed what you suggested, copied my PEM-formatted CA certificate to `/etc/pki/ca-trust/source/anchors/` and ran `sudo update-ca-trust extract` and it worked. 

I'm not expert in this area but could you try:
- See if it works without your internal CA certificate
- See if there is a valid PEM file in `/etc/ssl/certs/` folder
- See if OpenSSL can parse your `/etc/ssl/certs/ca-certificates.crt`: `openssl x509 -noout -verify -text -in /etc/ssl/certs/ca-certificates.crt`

**Comment by maxemontio** [comment] 2024-08-28 08:55
Thanks for suggestions @unexge, i have ran through your list:
- There is no difference without our internal CA, the error is the same
- Yes, it is in PEM format and it works with system as expected, there are no ssl errors while connecting to our other endpoints, it is valid
- OpenSSL parses it fine

**Comment by unexge** [comment] 2024-08-28 10:51
Hey @maxemontio, would you be able to share exact reproduction steps or your CA certificates for us to debug it?

**Comment by maxemontio** [comment] 2024-08-28 15:01
Unfortunately i can not share the certificates because of the company security policy, they don't make any difference anyway as i have checked.
But i can share userdata template from the nodes bootstrapping code (terraform):
```
post_bootstrap_user_data = <<EOT
cat << EOF > /etc/pki/ca-trust/source/anchors/ca.crt
${local.ca_chain}
EOF

cat << EOF > /etc/containerd/config.d/config.toml # here we add an OCI mirror only
${local.containerd_config}
EOF

update-ca-trust
systemctl restart containerd
EOT
```
That's all what happens to node, no more tuning.

**Comment by maxemontio** [comment] 2024-09-24 09:07
A little update here.

We updated our nodes to ami [v20240904](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20240904) and the problem has gone. I have no idea what it was.

**Comment by dannycjones** [comment] 2024-09-24 13:11
Glad to hear the problem has resolved itself!

Given the problem is currently gone, I'll close the issue. If it does reoccur (or any other issue), please do open a new issue.

**Closed by dannycjones** 2024-09-24 13:11 UTC
Labels: bug
